// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewaarsfeolhcfzenahqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YWFyc2Zlb2xoY2Z6ZW5haHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTk0NjcsImV4cCI6MjA3MzczNTQ2N30.5PKMsg-T8Xk6Jck_kYkUM1stQgbIRg1uKuG4sJfd18I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});